import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { conversationPreview } from './preview-conversations';

// Real public diff, sample conversations; no token, model, or provider writes.
const preview = await conversationPreview();
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHANGE_STACK_CHROMIUM });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, colorScheme: 'dark' });
page.setDefaultTimeout(10_000);
const errors: string[] = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (new URL(request.url()).origin !== preview.server.url.origin) errors.push(`Unexpected external request: ${request.url()}`); });
const inline = (id: string) => page.locator(`[data-testid=patch-pane] [data-thread-id="${id}"]`).first();
const view = page.getByTestId('conversation-view');
async function screenshot(name: string) { await page.waitForTimeout(250); await page.screenshot({ path: `dist/conversation-screenshots/${name}.png` }); }
async function openConversation() { await page.getByRole('button', { name: /^Conversation/ }).click(); await expect(view).toBeVisible(); }
async function closeConversation() { await view.getByRole('button', { name: 'Back to changes' }).click(); }
try {
  await mkdir('dist/conversation-screenshots', { recursive: true });
  await page.clock.install();
  await page.goto(preview.url);
  await page.getByRole('tab', { name: 'Unified', exact: true }).click();
  const open = inline('sample-open'), resolved = inline('sample-resolved');
  await expect(open).toBeVisible(); await expect(open.getByTestId('thread-comment')).toHaveCount(3);
  await expect(resolved.getByTestId('thread-comment')).toHaveCount(0);
  await screenshot('01-inline-open-and-resolved');
  await open.getByRole('button', { name: 'Reply', exact: true }).click();
  await open.getByRole('textbox').fill('I’ll add a test that keeps the active promise running while we clear the queued calls.');
  await screenshot('02-inline-reply');
  await page.getByRole('button', { name: 'Refresh conversation', exact: true }).click();
  await expect(open.getByRole('textbox')).toHaveValue('I’ll add a test that keeps the active promise running while we clear the queued calls.');
  await open.getByRole('textbox').fill('reject'); await open.getByRole('button', { name: 'Reply', exact: true }).click();
  await expect(open.getByRole('alert')).toContainText('draft has been kept'); await expect(open.getByRole('textbox')).toHaveValue('reject');
  await open.getByRole('textbox').fill('I’ll add that regression test.'); await open.getByRole('textbox').press('Control+Enter');
  await expect(open.getByTestId('thread-comment')).toHaveCount(4);
  await expect(open).toContainText('I’ll add that regression test.');
  await open.getByRole('button', { name: 'Resolve thread' }).click();
  await expect(open).toHaveAttribute('data-resolved', 'true'); await expect(open.getByTestId('thread-comment')).toHaveCount(0);
  await open.getByRole('button', { name: /^Expand thread/ }).click();
  await open.getByRole('button', { name: 'Reopen thread' }).click();
  await expect(open).toHaveAttribute('data-resolved', 'false'); await expect(open.getByTestId('thread-comment')).toHaveCount(4);
  await resolved.getByRole('button', { name: /^Expand thread/ }).click();
  await expect(resolved.getByTestId('thread-comment')).toHaveCount(2);
  await resolved.scrollIntoViewIfNeeded(); await screenshot('03-resolved-expanded');
  await page.getByTestId('layer-button').nth(1).click();
  await expect(inline('sample-single').getByTestId('thread-comment')).toHaveCount(1);
  await inline('sample-single').scrollIntoViewIfNeeded(); await screenshot('04-single-comment');
  await page.getByTestId('layer-button').nth(2).click();
  const long = inline('sample-long');
  await expect(long).toContainText('Show 6 earlier replies'); await expect(long.getByTestId('thread-comment')).toHaveCount(3);
  await long.scrollIntoViewIfNeeded(); await screenshot('05-long-thread');
  await long.getByRole('button', { name: 'Read full comment' }).click();
  await long.getByRole('button', { name: 'Show 6 earlier replies' }).click();
  await expect(long.getByTestId('thread-comment')).toHaveCount(9); await expect(long).toContainText('cleanup guidance');
  await long.getByRole('button', { name: 'Reply', exact: true }).click(); await long.getByRole('textbox').fill('Draft stays with this thread across layers.');
  await page.getByTestId('layer-button').first().click(); await page.getByTestId('layer-button').nth(2).click();
  await expect(inline('sample-long').getByRole('textbox')).toHaveValue('Draft stays with this thread across layers.');
  await inline('sample-long').getByRole('button', { name: 'Cancel', exact: true }).click();
  await openConversation(); await expect(view.getByTestId('review-thread')).toHaveCount(6); await screenshot('06-conversation-overview');
  await view.getByRole('tab', { name: 'Resolved 1', exact: true }).click(); await expect(view.getByTestId('review-thread')).toHaveCount(1);
  await view.getByRole('tab', { name: 'Open 4', exact: true }).click(); await expect(view.getByTestId('review-thread')).toHaveCount(4);
  const outdated = view.locator('[data-thread-id=sample-outdated]'); await expect(outdated).toContainText('Outdated'); await expect(outdated.getByRole('button', { name: 'View in diff' })).toHaveCount(0);
  await outdated.scrollIntoViewIfNeeded(); await screenshot('07-outdated-thread');
  await view.getByRole('tab', { name: 'Discussion', exact: true }).click(); await expect(view.getByTestId('review-thread')).toHaveCount(1);
  await view.getByRole('button', { name: 'New discussion' }).click(); await view.getByRole('textbox', { name: 'New discussion' }).fill('Ready to merge once the queue regression test lands.');
  await view.getByRole('button', { name: 'Post to GitHub' }).click(); await expect(view.getByTestId('review-thread')).toHaveCount(2);
  await screenshot('08-full-discussion');
  await view.getByRole('tab', { name: 'All', exact: true }).click();
  preview.mock.externalReply('sample-open'); await view.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(view.locator('[data-thread-id=sample-open]')).toContainText('Added the regression test');
  preview.mock.failNextLoad(); await view.getByRole('button', { name: 'Refresh', exact: true }).click(); await expect(view.getByRole('alert')).toContainText('last loaded comments');
  await expect(view.getByTestId('review-thread')).toHaveCount(7); await screenshot('09-refresh-error-keeps-comments');
  await view.getByRole('button', { name: 'Refresh', exact: true }).click(); await expect(view.getByRole('alert')).toHaveCount(0);
  preview.mock.externalReply('sample-single'); await page.clock.fastForward(5 * 60 * 1000);
  await expect(view.locator('[data-thread-id=sample-single]').getByTestId('thread-comment')).toHaveCount(2);
  await closeConversation(); await page.getByTestId('layer-button').first().click();
  const region = page.getByRole('region', { name: 'index.js', exact: true });
  await region.locator('[data-column-number="122"][data-line-type="change-addition"]').first().click();
  await expect(region.getByTestId('line-actions')).toBeVisible(); await region.getByRole('button', { name: 'Comment', exact: true }).click();
  await region.getByRole('textbox', { name: 'Comment', exact: true }).fill('New inline comment starts its own conversation.');
  await region.getByRole('button', { name: 'Post to GitHub' }).click();
  await expect(region.getByTestId('review-thread').filter({ hasText: 'New inline comment starts its own conversation.' })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(region.getByTestId('line-actions')).toHaveCount(0);
  expect(await inline('sample-open').evaluate(e => e.parentElement!.querySelectorAll('[data-testid=review-thread]').length)).toBe(2);
  await inline('sample-open').getByRole('button', { name: /^Collapse thread/ }).click();
  await screenshot('11-multiple-threads-on-one-line');
  await inline('sample-open').getByRole('button', { name: /^Expand thread/ }).click();
  await page.getByRole('tab', { name: 'Split', exact: true }).click();
  await expect(inline('sample-open')).toBeVisible();
  await screenshot('10-split-diff-threads');
  await openConversation();
  await view.getByRole('tab', { name: 'Open 5', exact: true }).click();
  await view.locator('[data-thread-id=sample-single]').getByRole('button', { name: 'View in diff' }).click();
  await expect(view).toHaveCount(0);
  await expect(inline('sample-single')).toBeVisible();
  await page.setViewportSize({ width: 1024, height: 900 }); await openConversation();
  await expect(view.getByRole('heading', { name: 'Review conversation' })).toBeVisible();
  if (errors.length) throw new Error(errors.join('; '));
  console.log('Conversation UI passed: inline posts, replies, retained drafts, resolve/reopen, filters, long/outdated threads, manual/5-minute refresh, failure recovery, and new discussions.');
} finally { await browser.close(); preview.server.stop(true); }
